export const cards = [
  "Im A Hitpan!",
  "Im A Hitpan!",
  "Cinammon Attack",
  "Cinammon Attack",
  "Cinammon Attack",
  "Spoon of Salt",
  "Spoon of Salt",
  "Spoon of Salt",
  "Mr. Liam's Kick and Heal!",
  "Mr. Liam's Kick and Steal!",
  "Mr. Liam's Kick and Lick!",
  "Sugar Rush",
  "Sugar Rush",
  "Hearty Meal",
  "Reorder",
  "Fast Food",
  "Manager Mode",
  "Heartier Meal",
  "Found The Lamb Sauce!",
  "Night Shift End",
  "Appetizer",
  "Dessert",
  "Kitchen Unite!",
  "Ass-asin",
  "Ass-asin",
  "Share Your Recipe",
  "Share Your Recipe",
  "Share Your Recipe",
];
