export const cards = [
  "I feel like a hero",
  "I feel like a hero",
  "I feel like a hero",
  "I feel like a hero",
  "I don't wanna feel your pain",
  "I don't wanna feel your pain",
  "I don't wanna feel your pain",
  "I don't wanna feel your pain",
  "Stop breaking me cause I'm already shattered",
  "Stop breaking me cause I'm already shattered",
  "Stop breaking me cause I'm already shattered",
  "Stop breaking me cause I'm already shattered",
  "Swing, swing",
  "Swing, swing",
  "Swing, swing",
  "Swing, swing",
  "It all keeps adding up",
  "It all keeps adding up",
  "Overthink",
  "Overthink",
  "Overthink",
  "Obsess: Because tonight will be the night that I will fall for you",
  "Share trauma",
  "Share trauma",
  "Share trauma",
  "Share Trauma",
  "Heartbroken",
  "Heartbroken",
];
