export const cards = [
  "Soul Chump Yum Yum",
  "Soul Chump Yum Yum",
  "Soul Strike",
  "Soul Strike with Sacrifice",
  "Soul Snack",
  "Soul Snack",
  "Soul Snack with Sacrifice",
  "A full soul is a lucky soul!",
  "hunger",
  "hunger",
  "lose some soul!",
  "lose some soul!",
  "get dem soulings around!",
  "Extreme Hunger",
  "Summon Soullings with Sacrifice",
  "Summon Soullings with Sacrifice",
  "Summon Soullings",
  "Summon Soullings",
  "A full soul is a luck soul!",
  "Extreme Hunger",
  "even souls gamble",
  "Suck dem Luck!",
  "Where are my SOULS!",
  "Where are my SOULS!",
  "am i hungry?",
  "steal some life",
  "REQUIEM OF SOULS",
  "Lez Syphon some Souls!",
];
